### ISSUE TITLE
File is reopened when snippet is inserted with palette

### ISSUE THREAD

**Issue by junichi11** [junichi11/netbeans-encoding-plugin#1]
#### my steps
1. open a file
2. open a palette window
3. insert snippet to editor
4. dialog for closing is opened

#### my environment
Product Version: NetBeans IDE 8.0 (Build 201403101706)
Java: 1.7.0_51; Java HotSpot(TM) Client VM 24.51-b03
Runtime: Java(TM) SE Runtime Environment 1.7.0_51-b13
System: Linux version 3.2.0-60-generic-pae running on i386; UTF-8;

**Comment by javatlacati** [comment]
Just checked and problem is solved as you point at 4bd7c25 this Issue can be closed.

**Comment by junichi11** [comment]
> Just checked and problem is solved as you point at 4bd7c25 this Issue can be closed.

:+1:
