### ISSUE TITLE
Possible to move the dropDownList between/below the others?

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#14]
I looked into the code a bit, I wanted to make a new PR to move the EncodingAccessories impl below or between the others, because your implementation breaks the ui and it doesn't looks very nice. Atm I don't know whether this is possible in general. Do you know it maybe?

Regards

Chris

**Comment by Chris2011** [comment]
Ok I found some solutions: http://stackoverflow.com/questions/24309517/custom-jfilechooser-how-to-add-jcombobox-into-the-jfilechooser or http://stackoverflow.com/questions/25786269/change-to-look-and-feel-of-customized-jfilechooser-raises-an-exception

I will dive into it later.

**Comment by junichi11** [comment]
Give it a try 1.4.5.1-dev : https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.4.5

**Comment by Chris2011** [comment]
It seems to work for me :). Great. Thx.
