### ISSUE TITLE
Please add a search field while typing

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#19]
The list is very long and it would be great, if there is a search field, which only appears while typing. NetBeans in general has this feature for some other panes like the project view or files or inside git etc. In IntelliJ there is the same functionality to change the encoding, looks similar to yours and they have this search field too.

It will not only jump to the result, it will shrink down the list to the result of the input of the field.

Regards

Chris

**Comment by junichi11** [comment]
Fixed. Please give it a try:
https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.4.2 (1.4.2.1-dev)

**NOTE:**
I will not fix the following:
- The list component is not resized
- The text field is not focused when the encoding label is clicked

**Comment by Chris2011** [comment]
I really appreciate your work. Thx.

Some things here:

* The inputfield should only comes up, when you type, it should be there in general.
* When I click in the field, nothing happens, it never gets the focus

Or I do smth wrong?

In WebStorm it comes up while typing:

In NetBeans, it comes up while typing: 

![searchwhiletyping](https://user-images.githubusercontent.com/795658/30435558-53699d40-996a-11e7-835d-75faa9fe359f.gif)

In WebStorm same:
![searchwhiletyping-webstorm](https://user-images.githubusercontent.com/795658/30435701-b55673d4-996a-11e7-9015-9c076d254dc9.gif)

In VS Code, it is always there, but on top, not on bottom, like in the Go To File or smth like that:

![image](https://user-images.githubusercontent.com/795658/30435743-d0d1f548-996a-11e7-9394-390645f97603.png)

So I'm fine with that, it is up to you. To make it more consistent, it should comes up while typing. Instead of this, I would like to see it on top.

but anyway, the initial problem, that the field never gets focus.

**Comment by junichi11** [comment]
> When I click in the field, nothing happens, it never gets the focus

Does it mean that you cannot type anything in the text field?
If so, I cannot reproduce it in my environment (Windows 10, Ubuntu).

**Comment by junichi11** [comment]
I've improved a bit (1.4.2.2-dev).

Although there is a minor problem, the text field would be focused by default.

**Comment by Chris2011** [comment]
> Does it mean that you cannot type anything in the text field?
> If so, I cannot reproduce it in my environment (Windows 10, Ubuntu).

Exactly, the focus is still inside the file, which is open. I will test it again with 1.4.2.3-dev.

**Comment by Chris2011** [comment]
Great work :)

**Comment by Chris2011** [comment]
Maybe esc should first cancel the search field and after hit essc again, the list should disappear, but i can create a new ticket if you want.

**Comment by junichi11** [comment]
> Great work :). Everything is working now as expected.

Great to hear :)

> Maybe esc should first cancel the search field and after hit essc again, the list should disappear,

I would not do it.

**Comment by Chris2011** [comment]
Ok, I'm fine with that.
