### ISSUE TITLE
Provide a version for the plugin center

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-encoding-plugin#2]
![image](https://cloud.githubusercontent.com/assets/1857095/5865203/f6d6cf16-a287-11e4-8d92-a3c86ec65730.png)

Your plugin is not yet in the plugin center. Can please sign it and upload it, so that it gets more attention? Thank you!

**Comment by junichi11** [comment]
I didn't publish this plugin on Plugin Portal for a few reasons. (e.g. I'm not original author, ...)

But I'll publish it there later ;)

Thanks.

**Comment by junichi11** [comment]
I'm sorry to be late...

I've just added this plugin to NetBeans Plugin Portal :) It will be shown after a few days.

**Comment by markiewb** [comment]
No problem. Now it is much better than never *g*

Best regards, markiewb

----- Ursprungligt meddelande -----
Från: "junichi11" <notifications@github.com>
Skickat: ‎24.‎09.‎2015 16:59
Till: "junichi11/netbeans-encoding-plugin" <netbeans-encoding-plugin@noreply.github.com>
Kopia: "markiewb" <benno.markiewicz@googlemail.com>
Ämne: Re: [netbeans-encoding-plugin] Provide a version for the plugincenter (#2)

I'm sorry to be late...
I've just added this plugin to NetBeans Plugin Portal :) It will be shown after a few days.
