### ISSUE TITLE
Please don't remove the dropDownList if the document lost focus

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#20]
It was a bit confusing for me, after I opened my output window and I tried to find the encoding dropDown again, until I realized, that it is only there if you are in a document. When you have a look into the other statusbar components like row/columnnumber, branch, etc, they are already there.

Of course it doesn't make sense for your dropDownList but I would prefer to not hide it, more to deactivate it. Sometimes it is not a good UX to hide stuff which you don't need but of course it is context sensitve.

Maybe it would be good to have a little tooltip on top of it, if you try to click it, that it says: No document focusable. Or smth like that.

Regards

Chris

**Comment by junichi11** [comment]
I know about that. But I want to avoid to do it because it may become the cause of confusing, sorry.

If I come up with a good idea, I'll do it.

**Comment by Chris2011** [comment]
I think now it is more confusing, because you are searching for it, if your document, doesn't have the focus anymore, only my opinion. But thx for the clarification.

**Comment by Chris2011** [comment]
The other part is, if you have a running process, which you can cancel and you are inside the document atm, you try to click on the cross of the process, the document losts the focus, the unicode drop down disappears and nothing happens, because you didn't hit the cross icon because it is moving. Now move the mouse and try it again.

Atm I don't have a good solution, only to let it there, not removing, only disabling with a tooltip that you first have to set the focus on the document. This will not break the UI and the behaviour.

**Comment by Chris2011** [comment]
I would like to bring this up again. As you can see it here: 
![normal](https://user-images.githubusercontent.com/795658/47314670-a0dfb080-d642-11e8-91c5-959dcf5c2e92.gif) NetBeans will still have the exact size of Insert and row:colum. So if I switch to the startpage, it will remove the text, which is ok and will not confuse someone, but will still have the width.

That is good, because it will not jump if you try to cancel a task, what I can't do it here, when you remove the text:
![encoding](https://user-images.githubusercontent.com/795658/47314755-e56b4c00-d642-11e8-8443-70ef5d9b1e6e.gif)

You see, that I want to cancel a task, which is not possible for the first time, because the Editor lost the focus and you remove the text, the field shrinks and I have to click again. This is a pain in the ass and sometimes I forget that, that your plugin acts like that. The same for any other statusline behaviour like show/switch branch.

So my solution is still that it should be there, I mean some others do the same, it shows the last entry from the lastFocusedEditor. If you still find it not good, what I can understand, I would prefer the other solution to have a fixed width of your label and remove only the text.

Here is a little workaround, not nice but works ok: https://bitbucket.org/jlahoda/crlf/src/default/crlf/src/com/kenai/pelmel/crlf/CRLFStatus.java?fileviewer=file-view-default#CRLFStatus.java-96

This plugin does the same, it uses JLabel("   ") for doing this, but I think it will make a calculation, hopefully.

What do you think?

**Comment by junichi11** [comment]
Just leave the icon.
https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.4.6 1.4.6.1-dev

**Comment by Chris2011** [comment]
What about not switching of the text and showing Encoding instead? It is still jumping. Or at least, it should be the same with as the longest element inside of it to prevent the jumping. It will then exact the same size of your popup.

**Comment by junichi11** [comment]
Give it a try.
https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.4.6 1.4.6.2-dev

**Comment by Chris2011** [comment]
Great, works as expected. Thx :)
