### ISSUE TITLE
Scrolling inside list of encoding types, scrolls the editor too

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#21]
If you scroll inside the list of encoding types, it will scroll the editor too. See my screencapture for this.

![encoding-scrolling-issue](https://user-images.githubusercontent.com/795658/32505202-e2230e44-c3e1-11e7-8d4b-3200ebe405a3.gif)

Regards

Chris

**Comment by junichi11** [comment]
I cannot reproduce it. Please try to disable the minimap plugin.

**Comment by Chris2011** [comment]
Will try thx.

**Comment by Chris2011** [comment]
Unfortunately still scrolling. Deactivated the outline plugin:
![still scrolling](https://user-images.githubusercontent.com/795658/47345218-7c1f2380-d6aa-11e8-87ae-a42863431f0b.gif)

**Comment by Chris2011** [comment]
Working fine with NB 10.0 VC2. Will check which plugin is the problem if it is still a problem.
