### ISSUE TITLE
Possible to not close/reopen the document to adjust the changes?

### ISSUE THREAD

**Issue by Chris2011** [junichi11/netbeans-encoding-plugin#23]
What the plugin does, after changing the encoding, it will close and open the file again, this is not a nice thing. I would prefer, that it should reload/refresh the area. This will first not having a big visual effect and second the cursor can stay as it is.

I know, that you can get the cursor position and set the cursor position afterwards but it will jumps again. Maybe two times. First reopen the file, second jump to the position.

I don't know whether this is possible in NetBeans or not, but I compared it with IntelliJ and VS Code and there is no real visual effect, no hazzle.

Cheers

Chris

**Comment by junichi11** [comment]
Development version: https://github.com/junichi11/netbeans-encoding-plugin/releases/tag/v1.7.0 1.7.0.1-dev

**Comment by Chris2011** [comment]
Great, it works like a charme. Thx :). You didn't push the code, right?

**Comment by junichi11** [comment]
Thanks for your verification. I'll push it later. I waited for verification by someone because I've implemented this using an ugly way(Maybe, there is no way to implement this using official public API, I suppose).

**Comment by junichi11** [comment]
Done.
