### ISSUE TITLE
Netbeans 16 Freezing after change encoding

### ISSUE THREAD

**Issue by Fabiobic** [junichi11/netbeans-encoding-plugin#25]
I am using the new version NetBeans 16, if I try to change the encoding, the drop-down menu appears, once the new encoding is selected, it is no longer possible to write and the old encoding box returns to the old one.
You have to close and reopen the NetBeans

**Comment by junichi11** [comment]
I can't reproduce it in NetBeans 17.
Is there an exception in your IDE log?
```
Product Version: Apache NetBeans IDE 17
Java: 11.0.17; OpenJDK 64-Bit Server VM 11.0.17+8-post-Ubuntu-1ubuntu222.04
Runtime: OpenJDK Runtime Environment 11.0.17+8-post-Ubuntu-1ubuntu222.04
System: Linux version 5.19.0-32-generic running on amd64; UTF-8; 
```

**Comment by Fabiobic** [comment]
I had an old version of Java.
I updated java and solved
thank you

**Comment by junichi11** [comment]
OK. Great to hear :)
