### ISSUE TITLE
File cannot be safely opened with encoding

### ISSUE THREAD

**Issue by kAlvaro** [junichi11/netbeans-encoding-plugin#6]
I have a project that mostly uses UTF-8 and is configured as such in NetBeans. But certain files (*.bat scripts) are encoded as Windows-1252. When I try to edit them I still get the infamous "File cannot be safely opened with encoding" warning dialogue. This happens in all operations I've tried: Navigate-> Go to File; double click on Project pane, etc.

"File-> Open in encoding" does the right thing but it breaks the streamlined workflow of using an IDE; it doesn't even default to current directory or project root.

I hope there's a chance to see this improved some day. Thank you!

**Comment by junichi11** [comment]
Probably, it is not this plugin's problem. 
Can you provide a simple project to reproduce it?(e.g. via GitHub public repo.)

**Comment by kAlvaro** [comment]
That's the standard NetBeans behaviour, sorry if I suggested it was due to your plug-in. Mi ticket is a feature request.

I've exported a sample project and uploaded it to http://alvaro.es/archivos/EncodingTest.zip . You can import it and try e.g. "Navigate-> Go to Symbol" with "test" as search string (or just click on files under "Site Root" tree).

**Comment by junichi11** [comment]
I'll look at it later. Thanks!

**Comment by junichi11** [comment]
I'm so sorry. I forgot this... I close this once, but If you have this problem still, please feel free to reopen it. Thanks.
